name: chapter 7
run-name: run by @${{ github.actor }}

on:
  workflow_dispatch:

jobs:
  call_workflow:
    uses: ./.github/workflows/ch7_call.yml
    with:
      title: "sandwitch"
      body: "its so healthy and delicious"

  print_title:
    runs-on: ubuntu-latest
    needs: call_workflow
    steps:
      - name: print title by id from previous workflow job
        id: title
        run: echo "titlex=${{ needs.call_workflow.outputs.title }}" >> "$GITHUB_OUTPUT"
      - name: print body by id from previous workflow job
        run: echo ${{ needs.call_workflow.outputs.body }}
      - name: calling value from previous step
        run: echo "printing title value:" ${{ steps.title.outputs.titlex }}
