name: arti-download

on:
  workflow_dispatch:

jobs:
  print-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v4

      - name: uploading artifacts
        uses: actions/upload-artifacts@v6
        with:
          name: archive.zip
          path: ./
      - name: downloading the artifacts from github repo
        uses: actions/download-artifact@v7.0.0
        with:
          name: archive.zip
          path: ./output

      - name: List current directory
        run: ls -l

      - name: List inside output
        run: ls -l ./output

      - name: Print README content
        run: cat ./output/README.md
