name: calling module
run-name: run by @${{ github.actor }}

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      body:
        required: true
        type: string
    outputs:
      title:
        description: "Returned title"
        value: ${{ jobs.build.outputs.title }}
      body:
        description: "Returns body"
        value: ${{ jobs.build.outputs.body }}

  workflow_dispatch:
    inputs:
      title:
        description: "title PIZZA"
        required: true
      body:
        description: "body SHAWARMA"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      title: ${{ steps.titleo.outputs.title }}
      body: ${{ steps.body.outputs.body }}
    steps:
      - name: print title
        id: "titleo"
        run: echo "title=${{ inputs.title }}" >> "$GITHUB_OUTPUT"
      - name: print body
        id: "body"
        run: echo "body=${{ inputs.body }}" >> "$GITHUB_OUTPUT"
