name: release
run-name: release by @${{ github.actor }}

on:
  push:
    branches: ["main", "dev"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: upload artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: archive.zip
          path: ./
