name: CI
run-name: pipline by @${{ github.actor }}
env:
  food: "shawarma"
  hoppy: "programmer"
  love_girls: true
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: downloading repo to the runner
        uses: actions/checkout@v3
      - name: printing pwd
        run: pwd
  personality:
    runs-on: ubuntu-latest
    steps:
      - name: check OS
        if: runner.os != 'Windows'
        run: echo "hello my dear linux $RUNNER_OS."
      - name: print custom repository variable
        run: echo "I like eating:" ${{ vars.CRAFTING_GH }}
      - name: print food
        run: echo ${{ env.food }}
      - name: print hoppy
        run: echo ${{ env.hoppy }}
      - name: print love girls
        run: echo absolutly ${{ env.love_girls }}
      - name: checking github secrets
        run: echo ${{ secrets.GITHUB_TOKEN }}
  report_url:
    runs-on: ubuntu-latest
    steps:
      - name: printing PIZZA TOKEN SECRET
        run: ${{ secrets.PIZZA_TOKEN }}
      - name: print url
        run: echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
